/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2017
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.ericsson.component.aia.sdk.templatemanager.views;

import com.ericsson.component.aia.sdk.templatemanager.exception.AppSdkException;

/**
 * @author ezsalro
 *
 */
public class ResponseError {

    private final String code;
    private final String internalRuntimeCode;

    /**
     * Default constructor
     */
    public ResponseError() {
        this.code = null;
        this.internalRuntimeCode = null;
    }

    /**
     * @param exception
     *            - The exception generated by the back-end.
     */
    public ResponseError(final Exception exception) {
        if (exception instanceof AppSdkException) {
            final AppSdkException appSdkException = (AppSdkException) exception;

            this.code = appSdkException.getCode();
            this.internalRuntimeCode = appSdkException.getRuntimeCode();

        } else {
            this.code = null;
            this.internalRuntimeCode = null;
        }
    }

    public String getCode() {
        return code;
    }

    public String getInternalRuntimeCode() {
        return internalRuntimeCode;
    }

}
